'use client';
import { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'es' | 'en';
interface LangContextType { lang: Lang; setLang: (l: Lang) => void; t: (key: string) => string; }

const translations: Record<Lang, Record<string, string>> = {
  es: {
    'nav.inicio': 'Inicio',
    'nav.solicitar': 'Solicitar Vuelo',
    'nav.registrar': 'Registrar Flota',
    'nav.servicios': 'Servicios',
    'nav.como': 'Cómo Funciona',
    'nav.ia': 'IA Responsable',
    'nav.empresa': 'Empresa',
    'nav.contacto': 'Contacto',
    'nav.cta': 'Solicitar Vuelo',
    'form.title': 'Solicitar vuelo',
    'form.subtitle': 'Completa el formulario con los detalles de tu operación. Evaluamos tu requerimiento y respondemos con opciones trazables en menos de 2 horas.',
    'form.badge1': 'Respuesta en 2h',
    'form.badge2': 'Revisión humana disponible',
    'form.badge3': 'Sin compromiso',
    'form.sec1': '01 — Datos de contacto',
    'form.nombre': 'Nombre completo *',
    'form.empresa': 'Empresa / Organización',
    'form.email': 'Email *',
    'form.telefono': 'Teléfono / WhatsApp',
    'form.sec2': '02 — Tipo de operación',
    'form.tipo': 'Tipo de operación *',
    'form.urgencia': 'Urgencia *',
    'form.sec3.vuelo': '03 — Detalles de la operación',
    'form.sec3.acmi': '03 — Especificaciones ACMI / Lease',
    'form.trayecto': 'Trayecto *',
    'form.origen': 'Origen *',
    'form.destino': 'Destino *',
    'form.fecha': 'Fecha de salida *',
    'form.fecha_regreso': 'Fecha de regreso *',
    'form.pax': 'Pasajeros / PAX',
    'form.carga': 'Carga / restricciones especiales',
    'form.acmi_tipo': 'Tipo de contrato *',
    'form.acmi_aircraft': 'Aeronave requerida',
    'form.acmi_bhr': 'Horas bloque estimadas / mes',
    'form.acmi_duracion': 'Duración del contrato',
    'form.acmi_aoc': 'AOC del Lessee',
    'form.acmi_base': 'Base operativa principal',
    'form.tramo': 'Tramo',
    'form.agregar_tramo': 'Agregar tramo',
    'form.sec4': '04 — Descripción adicional',
    'form.desc_vuelo': 'Describe tu operación con el mayor detalle posible: tipo de aeronave preferida, itinerario, condiciones especiales, etc.',
    'form.desc_acmi': 'Describe el requerimiento ACMI: rutas previstas, condiciones del contrato, certificaciones requeridas...',
    'form.consent': 'Acepto interactuar con un Hiperagente de Inteligencia Artificial.',
    'form.consent_desc': 'Entiendo que mi solicitud será procesada automáticamente por el sistema de IA de CharterLink. Puedo solicitar revisión humana en cualquier momento contactando a',
    'form.consent_error': '⚠ Debes aceptar el consentimiento para continuar.',
    'form.ia_notice': 'Estás interactuando con un Hiperagente de inteligencia artificial. Tu solicitud será procesada automáticamente. Si prefieres hablar con un humano, escríbenos a',
    'form.legal': 'CharterLink by TripLatam Ltd · UK Co. No. 15627355 · Datos tratados bajo UK GDPR.',
    'form.legal_link': '¿No estás de acuerdo con una decisión automática? Solicita revisión humana.',
    'form.submit': 'Enviar solicitud',
    'form.sending': 'Enviando...',
    'form.privacy': 'Al enviar, aceptas que procesemos tus datos para evaluar tu solicitud operacional.',
    'form.success_title': 'Solicitud enviada',
    'form.success_msg': 'Tu solicitud fue enviada correctamente. Te contactaremos en menos de 2 horas.',
    'form.error_msg': 'Hubo un error al enviar. Escríbenos directamente a charter@triplatam.com',
    'form.select': 'Seleccionar...',
    'tray.ow': 'One Way (OW)',
    'tray.rt': 'Round Trip (RT)',
    'tray.multi': 'Multi-leg',
    'urg.1': 'Urgente (< 24h)',
    'urg.2': 'Alta (1-3 días)',
    'urg.3': 'Normal (3-7 días)',
    'urg.4': 'Planificado (> 7 días)',
    'tipo.1': 'Charter Pasajeros',
    'tipo.2': 'ACMI / Wet Lease',
    'tipo.3': 'Carga General',
    'tipo.4': 'Carga Urgente',
    'tipo.5': 'Médico / MEDEVAC',
    'tipo.6': 'Humanitario',
    'tipo.7': 'Gobierno / Militar',
    'tipo.8': 'Deportivo',
    'tipo.9': 'Otro',
    'acmi.1': 'Wet Lease (ACMI completo)',
    'acmi.2': 'Dry Lease (solo aeronave)',
    'acmi.3': 'Damp Lease (aeronave + tripulación)',
    'dur.1': '1 a 3 meses',
    'dur.2': '3 a 6 meses',
    'dur.3': '6 a 12 meses',
    'dur.4': 'Más de 12 meses',
    'dur.5': 'Operación ad-hoc',
  },
  en: {
    'nav.inicio': 'Home',
    'nav.solicitar': 'Request Flight',
    'nav.registrar': 'Register Fleet',
    'nav.servicios': 'Services',
    'nav.como': 'How It Works',
    'nav.ia': 'Responsible AI',
    'nav.empresa': 'Company',
    'nav.contacto': 'Contact',
    'nav.cta': 'Request Flight',
    'form.title': 'Request a flight',
    'form.subtitle': 'Fill in the form with your operation details. We evaluate your requirement and respond with traceable options in under 2 hours.',
    'form.badge1': 'Response in 2h',
    'form.badge2': 'Human review available',
    'form.badge3': 'No commitment',
    'form.sec1': '01 — Contact details',
    'form.nombre': 'Full name *',
    'form.empresa': 'Company / Organization',
    'form.email': 'Email *',
    'form.telefono': 'Phone / WhatsApp',
    'form.sec2': '02 — Operation type',
    'form.tipo': 'Operation type *',
    'form.urgencia': 'Urgency *',
    'form.sec3.vuelo': '03 — Operation details',
    'form.sec3.acmi': '03 — ACMI / Lease specifications',
    'form.trayecto': 'Route type *',
    'form.origen': 'Origin *',
    'form.destino': 'Destination *',
    'form.fecha': 'Departure date *',
    'form.fecha_regreso': 'Return date *',
    'form.pax': 'Passengers / PAX',
    'form.carga': 'Cargo / special restrictions',
    'form.acmi_tipo': 'Contract type *',
    'form.acmi_aircraft': 'Required aircraft',
    'form.acmi_bhr': 'Estimated block hours / month',
    'form.acmi_duracion': 'Contract duration',
    'form.acmi_aoc': 'Lessee AOC',
    'form.acmi_base': 'Main operating base',
    'form.tramo': 'Leg',
    'form.agregar_tramo': 'Add leg',
    'form.sec4': '04 — Additional description',
    'form.desc_vuelo': 'Describe your operation in as much detail as possible: preferred aircraft type, itinerary, special conditions, etc.',
    'form.desc_acmi': 'Describe the ACMI requirement: planned routes, contract conditions, required certifications...',
    'form.consent': 'I agree to interact with an Artificial Intelligence Hyperagent.',
    'form.consent_desc': 'I understand that my request will be processed automatically by the CharterLink AI system. I can request human review at any time by contacting',
    'form.consent_error': '⚠ You must accept the consent to continue.',
    'form.ia_notice': 'You are interacting with an Artificial Intelligence Hyperagent. Your request will be processed automatically. If you prefer to speak with a human, write to us at',
    'form.legal': 'CharterLink by TripLatam Ltd · UK Co. No. 15627355 · Data processed under UK GDPR.',
    'form.legal_link': 'Do you disagree with an automatic decision? Request human review.',
    'form.submit': 'Send request',
    'form.sending': 'Sending...',
    'form.privacy': 'By submitting, you agree that we process your data to evaluate your operational request.',
    'form.success_title': 'Request sent',
    'form.success_msg': 'Your request was sent successfully. We will contact you in less than 2 hours.',
    'form.error_msg': 'There was an error sending. Write to us directly at charter@triplatam.com',
    'form.select': 'Select...',
    'tray.ow': 'One Way (OW)',
    'tray.rt': 'Round Trip (RT)',
    'tray.multi': 'Multi-leg',
    'urg.1': 'Urgent (< 24h)',
    'urg.2': 'High (1-3 days)',
    'urg.3': 'Normal (3-7 days)',
    'urg.4': 'Planned (> 7 days)',
    'tipo.1': 'Passenger Charter',
    'tipo.2': 'ACMI / Wet Lease',
    'tipo.3': 'General Cargo',
    'tipo.4': 'Urgent Cargo',
    'tipo.5': 'Medical / MEDEVAC',
    'tipo.6': 'Humanitarian',
    'tipo.7': 'Government / Military',
    'tipo.8': 'Sports',
    'tipo.9': 'Other',
    'acmi.1': 'Wet Lease (full ACMI)',
    'acmi.2': 'Dry Lease (aircraft only)',
    'acmi.3': 'Damp Lease (aircraft + crew)',
    'dur.1': '1 to 3 months',
    'dur.2': '3 to 6 months',
    'dur.3': '6 to 12 months',
    'dur.4': 'More than 12 months',
    'dur.5': 'Ad-hoc operation',
  }
};

const LangContext = createContext<LangContextType>({ lang: 'es', setLang: () => {}, t: (k) => k });

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('es');
  const t = (key: string) => translations[lang][key] ?? key;
  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
