'use client';
import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Lang = 'es' | 'en';
interface LangContextType { lang: Lang; setLang: (l: Lang) => void; t: (key: string) => string; }

const translations: Record<Lang, Record<string, string>> = {
  es: {
    'nav.inicio': 'Inicio', 'nav.solicitar': 'Solicitar Vuelo', 'nav.registrar': 'Registrar Flota',
    'nav.servicios': 'Servicios', 'nav.como': 'Cómo Funciona', 'nav.ia': 'IA Responsable',
    'nav.empresa': 'Empresa', 'nav.contacto': 'Contacto', 'nav.cta': 'Solicitar Vuelo',
    'home.tag': 'Charter · ACMI · Cargo · Operaciones especiales',
    'home.h1a': 'Flota ociosa.', 'home.h1b': 'Demanda real.',
    'home.sub1': 'Conectamos demanda aérea con flota disponible en menos tiempo.',
    'home.sub2': 'Vuelos charter, ACMI/Wet Lease, carga y operaciones especiales coordinadas con trazabilidad, criterio operacional y revisión humana disponible.',
    'home.btn1': 'Solicitar vuelo', 'home.btn2': 'Registrar flota',
    'home.badge1': 'RESPUESTA 24/7', 'home.badge2': 'COTIZACIÓN EN 2H', 'home.badge3': 'REVISIÓN HUMANA DISPONIBLE',
    'home.hub.tag': 'Aviation Intelligence Hub', 'home.hub.title': 'Aviation Intelligence Hub',
    'home.hub.desc': 'Centralizamos solicitudes de vuelo, disponibilidad de flota y evaluación operacional para conectar requerimientos reales con capacidad aérea compatible.',
    'home.hub.i1t': 'Charter y ACMI', 'home.hub.i1d': 'Capacidad para operaciones dedicadas, wet lease y cobertura de demanda.',
    'home.hub.i2t': 'Carga y operaciones críticas', 'home.hub.i2d': 'Evaluación rápida para rutas, carga urgente, pasajeros o misiones especiales.',
    'home.hub.i3t': 'Trazabilidad y revisión humana', 'home.hub.i3d': 'Registro del requerimiento, criterios de evaluación y revisión experta cuando corresponde.',
    'home.hub.footer': 'Respuesta operacional 24/7 con evaluación acelerada para solicitudes urgentes.',
    'home.stat1': 'Operadores globales', 'home.stat2': 'Países cubiertos', 'home.stat3': 'Respuesta operacional', 'home.stat4': 'Cotización urgente',
    'home.demand.tag': 'Demanda', 'home.demand.title': '¿Necesitas volar?',
    'home.demand.desc': 'Para empresas, agencias, gobiernos, deportes, logística y misiones especiales que necesitan una aeronave adecuada sin perder tiempo.',
    'home.demand.i1': 'Charter corporativo y ejecutivo', 'home.demand.i2': 'Grupos y delegaciones',
    'home.demand.i3': 'Carga urgente y especializada', 'home.demand.i4': 'Operaciones médicas o humanitarias',
    'home.demand.btn': 'Solicitar vuelo',
    'home.bridge': 'FlyTriplatam conecta ambos lados con criterio operacional y trazabilidad.',
    'home.offer.tag': 'Oferta', 'home.offer.title': '¿Tienes flota disponible?',
    'home.offer.desc': 'Para lessors, operadores, charter providers y dueños de flota que buscan exposición a demanda real y capacidad ociosa.',
    'home.offer.i1': 'ACMI / Wet Lease', 'home.offer.i2': 'Full Charter', 'home.offer.i3': 'Cargo Charter', 'home.offer.i4': 'Capacidad ociosa / disponibilidad',
    'home.offer.btn': 'Registrar flota',
    'home.srv.tag': 'Servicios', 'home.srv.title': 'Soluciones de aviación charter',
    'home.srv.desc': 'Operaciones charter, ACMI, carga y vuelos especializados para demanda crítica y coordinada.',
    'home.srv.link': 'Ver servicios',
    'home.srv.1t': 'ACMI / Wet Lease', 'home.srv.1d': 'Capacidad con aeronave, tripulación, mantenimiento y seguros para cubrir picos de demanda o continuidad operativa.',
    'home.srv.2t': 'Full Charter', 'home.srv.2d': 'Operaciones dedicadas para grupos, eventos, delegaciones y movimientos de alto valor con coordinación end to end.',
    'home.srv.3t': 'Carga y logística', 'home.srv.3d': 'Carga general, urgente, farmacéutica, perecedera y de alto valor con foco en trazabilidad y tiempos críticos.',
    'home.srv.4t': 'Ejecutivo y médico', 'home.srv.4d': 'Jets ejecutivos, ambulancia aérea y traslados médicos con coordinación experta y revisión humana disponible.',
    'home.coord.tag': 'Coordinación operacional', 'home.coord.title': 'Cada solicitud se evalúa con criterio operativo',
    'home.coord.desc1': 'Cada solicitud se evalúa considerando ruta, urgencia, tipo de operación, disponibilidad y restricciones técnicas.',
    'home.coord.desc2': 'No conectamos formularios con bases de datos. Conectamos requerimientos reales con capacidad operacional compatible.',
    'home.coord.i1t': 'Demanda validada', 'home.coord.i1d': 'La solicitud entra con señales básicas de fit operativo.',
    'home.coord.i2t': 'Capacidad compatible', 'home.coord.i2d': 'Se contrasta con capacidad disponible y tipo de aeronave.',
    'home.coord.i3t': 'Revisión humana disponible', 'home.coord.i3d': 'Se activa si el caso requiere criterio experto.',
    'home.how.tag': 'Cómo funciona', 'home.how.title': 'Convertimos una necesidad aérea en opciones trazables',
    'home.how.desc': 'Capturamos información, evaluamos oferta y devolvemos opciones con supervisión humana disponible cuando el caso lo requiere.',
    'home.how.link': 'Ver proceso completo',
    'home.how.1t': 'Recibimos tu requerimiento', 'home.how.1d': 'Capturamos ruta, urgencia, tipo de operación, pasajeros/carga y restricciones.',
    'home.how.2t': 'Buscamos aeronave disponible', 'home.how.2d': 'Evaluamos capacidad compatible dentro de una red global de operadores y proveedores.',
    'home.how.3t': 'Entregamos opciones trazables', 'home.how.3d': 'Presentamos alternativas con revisión humana disponible para casos críticos.',
    'home.trust.tag': 'Confianza operacional',
    'home.trust.title': 'Procesos diseñados para trazabilidad, protección de datos, revisión humana y mejora continua.',
    'home.trust.desc1': 'La plataforma opera con controles visibles y un flujo documental pensado para entornos B2B sensibles.',
    'home.trust.desc2': 'Diseñamos el flujo para que la operación mantenga control, trazabilidad y revisión humana cuando el caso lo justifica.',
    'home.trust.link': 'Ver IA responsable',
    'home.trust.i1t': 'Registro y operación', 'home.trust.i1d': 'TripLatam Ltd · UK Co. No. 15627355',
    'home.trust.i2t': 'Protección de datos', 'home.trust.i2d': 'Tratamiento responsable de solicitudes y datos comerciales.',
    'home.trust.i3t': 'Trazabilidad', 'home.trust.i3d': 'Registro claro de solicitud, evaluación y propuesta.',
    'home.trust.i4t': 'Revisión humana', 'home.trust.i4d': 'Escalamiento disponible para operaciones críticas.',
    'home.trust.i5t': 'Calidad', 'home.trust.i5d': 'Procesos alineados con buenas prácticas de gestión.',
    'home.trust.i6t': 'IA responsable', 'home.trust.i6d': 'Hoja de ruta hacia ISO/IEC 42001.',
    'home.cta.tag': 'Siguiente paso', 'home.cta.title': 'Solicita una operación o registra capacidad disponible.',
    'home.cta.desc': 'Solicita una operación o registra capacidad disponible en la red FlyTriplatam.',
    'home.cta.btn1': 'Solicitar vuelo', 'home.cta.btn2': 'Registrar flota',
    'home.cta.footer': 'Respuesta operacional 24/7 · Revisión humana disponible · Trazabilidad y control',
    'srv.tag': 'Servicios', 'srv.title': 'Soluciones de aviación charter',
    'srv.desc': 'Operaciones charter, ACMI, carga y vuelos especializados para demanda crítica y coordinada. Cada operación evaluada con criterio experto.',
    'srv.inc': 'Incluye', 'srv.cta.title': '¿Necesitas una de estas soluciones?',
    'srv.cta.desc': 'Envía tu requerimiento y evaluamos la operación con criterio experto. Respuesta en menos de 2 horas.',
    'srv.cta.btn1': 'Solicitar vuelo', 'srv.cta.btn2': 'Contactar',
    'srv.1t': 'ACMI / Wet Lease', 'srv.1d': 'Capacidad con aeronave, tripulación, mantenimiento y seguros para cubrir picos de demanda o continuidad operativa. Ideal para aerolíneas en crecimiento, operaciones estacionales o sustitución de flota.',
    'srv.1i1': 'Aeronave + tripulación + mantenimiento + seguros', 'srv.1i2': 'Rutas definidas por el arrendatario', 'srv.1i3': 'Contratos flexibles por temporada o corto plazo', 'srv.1i4': 'Ideal para cubrir picos de demanda o ETOPS',
    'srv.2t': 'Full Charter', 'srv.2d': 'Operaciones dedicadas para grupos, eventos, delegaciones y movimientos de alto valor con coordinación end to end. Vuelo exclusivo para tu operación.',
    'srv.2i1': 'Aeronave exclusiva para tu operación', 'srv.2i2': 'Itinerario personalizado', 'srv.2i3': 'Coordinación completa desde origen', 'srv.2i4': 'Manejo de PRM, VIP y protocolos especiales',
    'srv.3t': 'Carga y logística', 'srv.3d': 'Carga general, urgente, farmacéutica, perecedera y de alto valor con foco en trazabilidad y tiempos críticos. Cadena de frío y manejo de mercancías peligrosas.',
    'srv.3i1': 'Carga general y urgente', 'srv.3i2': 'Productos farmacéuticos (temperatura controlada)', 'srv.3i3': 'Mercancías peligrosas según IATA DGR', 'srv.3i4': 'Alta trazabilidad y documentación',
    'srv.4t': 'Ejecutivo y médico', 'srv.4d': 'Jets ejecutivos, ambulancia aérea y traslados médicos con coordinación experta y revisión humana disponible.',
    'srv.4i1': 'Jets ejecutivos y VIP', 'srv.4i2': 'Ambulancia aérea (MEDEVAC)', 'srv.4i3': 'Repatriación de pacientes', 'srv.4i4': 'Coordinación con equipos médicos a bordo',
    'how.tag': 'Cómo funciona', 'how.title': 'Convertimos una necesidad aérea en opciones trazables',
    'how.desc': 'Capturamos información, evaluamos oferta y devolvemos opciones con supervisión humana disponible cuando el caso lo requiere.',
    'how.coord.tag': 'Coordinación operacional', 'how.coord.title': 'Cada solicitud se evalúa con criterio operativo',
    'how.coord.desc': 'No conectamos formularios con bases de datos. Conectamos requerimientos reales con capacidad operacional compatible.',
    'how.coord.i1t': 'Demanda validada', 'how.coord.i1d': 'La solicitud entra con señales básicas de fit operativo.',
    'how.coord.i2t': 'Capacidad compatible', 'how.coord.i2d': 'Se contrasta con capacidad disponible y tipo de aeronave.',
    'how.coord.i3t': 'Revisión humana disponible', 'how.coord.i3d': 'Se activa si el caso requiere criterio experto.',
    'how.btn1': 'Solicitar vuelo', 'how.btn2': 'Ver IA responsable',
    'how.1t': 'Recibimos tu requerimiento', 'how.1d': 'Capturamos ruta, urgencia, tipo de operación, pasajeros o carga, y restricciones técnicas o regulatorias.',
    'how.1i1': 'Formulario de solicitud estructurado', 'how.1i2': 'Señales básicas de fit operativo', 'how.1i3': 'Clasificación automática por urgencia', 'how.1i4': 'Verificación inicial del requerimiento',
    'how.2t': 'Buscamos aeronave disponible', 'how.2d': 'Evaluamos capacidad compatible dentro de una red global de operadores, lessors y charter providers.',
    'how.2i1': 'Contraste con flota disponible registrada', 'how.2i2': 'Evaluación de ruta y restricciones', 'how.2i3': 'Identificación de operadores compatibles', 'how.2i4': 'Análisis de tiempos de respuesta',
    'how.3t': 'Evaluación operacional', 'how.3d': 'Cada solicitud se evalúa considerando ruta, urgencia, tipo de operación, disponibilidad y restricciones técnicas.',
    'how.3i1': 'Criterio operativo experto', 'how.3i2': 'Validación de fit aeronave-ruta', 'how.3i3': 'Revisión humana para casos críticos', 'how.3i4': 'Escalamiento para operaciones complejas',
    'how.4t': 'Entregamos opciones trazables', 'how.4d': 'Presentamos alternativas con revisión humana disponible para casos críticos, con trazabilidad completa del proceso.',
    'how.4i1': 'Propuesta con opciones comparables', 'how.4i2': 'Registro de evaluación visible', 'how.4i3': 'Supervisión humana en casos críticos', 'how.4i4': 'Documentación del proceso completo',
    'emp.tag': 'Empresa', 'emp.title': 'FlyTriplatam',
    'emp.desc': 'Aviation Intelligence Hub operado por TripLatam Ltd. Conectamos demanda aérea global con capacidad disponible de forma ágil, trazable y responsable.',
    'emp.mis.tag': 'Nuestra misión', 'emp.mis.title': 'Reducir la fricción entre demanda aérea real y capacidad disponible.',
    'emp.mis.p1': 'El mercado de aviación charter opera con ineficiencias estructurales: flota ociosa que no encuentra demanda, y operaciones que no encuentran aeronaves adecuadas en tiempo.',
    'emp.mis.p2': 'FlyTriplatam existe para resolver esa brecha con criterio operacional, trazabilidad y revisión humana disponible cuando el caso lo requiere.',
    'emp.dif.tag': 'Qué nos diferencia',
    'emp.dif.1': 'No somos un marketplace sin criterio: evaluamos cada solicitud operacionalmente.',
    'emp.dif.2': 'Revisión humana disponible para casos complejos o críticos.',
    'emp.dif.3': 'Trazabilidad completa del proceso: el solicitante sabe cómo se evaluó su operación.',
    'emp.dif.4': 'Red global de operadores con presencia en más de 80 países.',
    'emp.dif.5': 'Respuesta en menos de 2 horas para solicitudes urgentes.',
    'emp.legal.tag': 'Registro legal', 'emp.legal.reg': 'TripLatam Ltd', 'emp.legal.ops': 'Operaciones', 'emp.legal.comp': 'Cumplimiento',
    'emp.btn1': 'Contactar', 'emp.btn2': 'IA Responsable',
    'cont.tag': 'Contacto', 'cont.title': 'Contacto',
    'cont.desc': 'Respondemos por los canales oficiales del sitio. Para solicitudes de vuelo, usa el formulario estructurado para una respuesta más rápida.',
    'cont.c1t': 'Solicitud de vuelo', 'cont.c1d': 'Para vuelos charter, ACMI, carga y operaciones especiales.', 'cont.c1cta': 'Enviar email',
    'cont.c2t': 'WhatsApp operativo', 'cont.c2d': 'Canal directo para solicitudes urgentes y consultas operacionales.', 'cont.c2cta': 'Abrir WhatsApp',
    'cont.c3t': 'Alianzas y operadores', 'cont.c3d': 'Para lessors, operadores y charter providers que buscan asociarse.', 'cont.c3cta': 'Enviar email',
    'cont.form.tag': 'Vía formulario', 'cont.form.title': 'Solicitud estructurada',
    'cont.form.desc': 'Para operaciones charter, ACMI o carga, el formulario estructurado nos permite evaluar tu requerimiento con más detalle y responder en menos de 2 horas.',
    'cont.form.btn1': 'Formulario de solicitud de vuelo', 'cont.form.btn2': 'Registrar flota disponible',
    'ia.tag': 'IA Responsable', 'ia.title': 'IA Responsable',
    'ia.desc': 'Procesos diseñados para trazabilidad, protección de datos, revisión humana y mejora continua. La plataforma opera con controles visibles y un flujo documental pensado para entornos B2B sensibles.',
    'ia.p1t': 'Transparencia operativa', 'ia.p1d': 'Los procesos de evaluación son visibles y trazables. El solicitante puede entender cómo se evaluó su requerimiento y qué criterios se aplicaron.',
    'ia.p2t': 'Revisión humana disponible', 'ia.p2d': 'Para operaciones críticas, complejas o sensibles, un experto humano revisa y valida el proceso antes de presentar opciones.',
    'ia.p3t': 'Protección de datos', 'ia.p3d': 'Los datos comerciales y operacionales se tratan con responsabilidad, bajo UK GDPR, con acceso limitado y flujos documentados.',
    'ia.p4t': 'Audit logs y trazabilidad', 'ia.p4d': 'Registro claro de solicitud, evaluación y propuesta. Cada operación deja una huella documental verificable.',
    'ia.design.tag': 'Principio de diseño', 'ia.design.quote': 'Diseñamos el flujo para que la operación mantenga control, trazabilidad y revisión humana cuando el caso lo justifica.',
    'ia.road.tag': 'Estado y hoja de ruta',
    'ia.r1l': 'Revisión humana disponible', 'ia.r1d': 'Escalamiento manual activo para operaciones críticas.',
    'ia.r2l': 'Audit logs básicos', 'ia.r2d': 'Registro de solicitudes y respuestas en cada operación.',
    'ia.r3l': 'UK GDPR compliance', 'ia.r3d': 'Tratamiento de datos conforme a la normativa británica.',
    'ia.r4l': 'ISO 9001 alignment', 'ia.r4d': 'Procesos de calidad alineados con la norma internacional.',
    'ia.r5l': 'ISO/IEC 42001 certification', 'ia.r5d': 'Hoja de ruta hacia la certificación de sistemas de IA.',
    'ia.r6l': 'Explainability reports', 'ia.r6d': 'Reportes de explicabilidad para cada evaluación automática.',
    'ia.status.active': 'Activo', 'ia.status.process': 'En proceso', 'ia.status.roadmap': 'Roadmap',
    'ia.comp.tag': 'Registro y cumplimiento', 'ia.comp.std': 'Estándares',
    'ia.btn1': 'Ver proceso completo', 'ia.btn2': 'Contactar para más información',
    'reg.tag': 'Oferta', 'reg.title': 'Registrar flota',
    'reg.desc': 'Registra tu aeronave o flota en la red FlyTriplatam y accede a demanda real de vuelos charter, ACMI y carga.',
    'reg.badge1': 'Red global de demanda', 'reg.badge2': 'Sin costos de acceso', 'reg.badge3': 'Revisión humana del match',
    'reg.sec1': '01 — Datos del operador', 'reg.sec2': '02 — Detalles de la aeronave', 'reg.sec3': '03 — Modalidades disponibles', 'reg.sec4': '04 — Información adicional',
    'reg.nombre': 'Nombre de contacto *', 'reg.empresa': 'Empresa / Operador *', 'reg.email': 'Email *',
    'reg.telefono': 'Teléfono / WhatsApp', 'reg.web': 'Sitio web',
    'reg.aeronave': 'Tipo de aeronave *', 'reg.matricula': 'Matrícula / Registro', 'reg.anio': 'Año de fabricación',
    'reg.capacidad': 'Capacidad (PAX o kg)', 'reg.bases': 'Bases operativas', 'reg.disponibilidad': 'Disponibilidad próxima',
    'reg.desc_placeholder': 'Certificaciones, rutas habituales, condiciones especiales de operación, restricciones...',
    'reg.submit': 'Registrar flota', 'reg.sending': 'Enviando...', 'reg.select': 'Seleccionar...',
    'reg.privacy': 'Al registrar, aceptas que usemos esta información para conectarte con demanda compatible en la red FlyTriplatam.',
    'reg.success_title': 'Flota registrada', 'reg.success_msg': 'Tu flota fue registrada. Nuestro equipo revisará la información y se pondrá en contacto contigo.',
    'reg.error_msg': 'Error al enviar. Escríbenos a charter@triplatam.com',
    'form.title': 'Solicitar vuelo', 'form.subtitle': 'Completa el formulario con los detalles de tu operación. Evaluamos tu requerimiento y respondemos con opciones trazables en menos de 2 horas.',
    'form.badge1': 'Respuesta en 2h', 'form.badge2': 'Revisión humana disponible', 'form.badge3': 'Sin compromiso',
    'form.sec1': '01 — Datos de contacto', 'form.nombre': 'Nombre completo *', 'form.empresa': 'Empresa / Organización',
    'form.email': 'Email *', 'form.telefono': 'Teléfono / WhatsApp', 'form.sec2': '02 — Tipo de operación',
    'form.tipo': 'Tipo de operación *', 'form.urgencia': 'Urgencia *',
    'form.sec3.vuelo': '03 — Detalles de la operación', 'form.sec3.acmi': '03 — Especificaciones ACMI / Lease',
    'form.trayecto': 'Trayecto *', 'form.origen': 'Origen *', 'form.destino': 'Destino *',
    'form.fecha': 'Fecha de salida *', 'form.fecha_regreso': 'Fecha de regreso *',
    'form.pax': 'Pasajeros / PAX', 'form.carga': 'Carga / restricciones especiales',
    'form.acmi_tipo': 'Tipo de contrato *', 'form.acmi_aircraft': 'Aeronave requerida',
    'form.acmi_bhr': 'Horas bloque estimadas / mes', 'form.acmi_duracion': 'Duración del contrato',
    'form.acmi_aoc': 'AOC del Lessee', 'form.acmi_base': 'Base operativa principal',
    'form.tramo': 'Tramo', 'form.agregar_tramo': 'Agregar tramo', 'form.sec4': '04 — Descripción adicional',
    'form.desc_vuelo': 'Describe tu operación con el mayor detalle posible: tipo de aeronave preferida, itinerario, condiciones especiales, etc.',
    'form.desc_acmi': 'Describe el requerimiento ACMI: rutas previstas, condiciones del contrato, certificaciones requeridas...',
    'form.consent': 'Acepto interactuar con un Hiperagente de Inteligencia Artificial.',
    'form.consent_desc': 'Entiendo que mi solicitud será procesada automáticamente por el sistema de IA de CharterLink. Puedo solicitar revisión humana en cualquier momento contactando a',
    'form.consent_error': '⚠ Debes aceptar el consentimiento para continuar.',
    'form.ia_notice': 'Estás interactuando con un Hiperagente de inteligencia artificial. Tu solicitud será procesada automáticamente. Si prefieres hablar con un humano, escríbenos a',
    'form.legal': 'CharterLink by TripLatam Ltd · UK Co. No. 15627355 · Datos tratados bajo UK GDPR.',
    'form.legal_link': '¿No estás de acuerdo con una decisión automática? Solicita revisión humana.',
    'form.submit': 'Enviar solicitud', 'form.sending': 'Enviando...', 'form.privacy': 'Al enviar, aceptas que procesemos tus datos para evaluar tu solicitud operacional.',
    'form.success_title': 'Solicitud enviada', 'form.success_msg': 'Tu solicitud fue enviada correctamente. Te contactaremos en menos de 2 horas.',
    'form.error_msg': 'Hubo un error al enviar. Escríbenos directamente a charter@triplatam.com', 'form.select': 'Seleccionar...',
    'tray.ow': 'One Way (OW)', 'tray.rt': 'Round Trip (RT)', 'tray.multi': 'Multi-leg',
    'urg.1': 'Urgente (< 24h)', 'urg.2': 'Alta (1-3 días)', 'urg.3': 'Normal (3-7 días)', 'urg.4': 'Planificado (> 7 días)',
    'tipo.1': 'Charter Pasajeros', 'tipo.2': 'ACMI / Wet Lease', 'tipo.3': 'Carga General', 'tipo.4': 'Carga Urgente',
    'tipo.5': 'Médico / MEDEVAC', 'tipo.6': 'Humanitario', 'tipo.7': 'Gobierno / Militar', 'tipo.8': 'Deportivo', 'tipo.9': 'Otro',
    'acmi.1': 'Wet Lease (ACMI completo)', 'acmi.2': 'Dry Lease (solo aeronave)', 'acmi.3': 'Damp Lease (aeronave + tripulación)',
    'dur.1': '1 a 3 meses', 'dur.2': '3 a 6 meses', 'dur.3': '6 a 12 meses', 'dur.4': 'Más de 12 meses', 'dur.5': 'Operación ad-hoc',
    'aeronave.1': 'Narrow-body (B737, A320 family)', 'aeronave.2': 'Wide-body (B767, A330)', 'aeronave.3': 'Regional Jet (E190, CRJ)',
    'aeronave.4': 'Turboprop (ATR, Dash 8)', 'aeronave.5': 'Carguero (B747F, B777F)', 'aeronave.6': 'Jet Ejecutivo', 'aeronave.7': 'Helicóptero', 'aeronave.8': 'Otro',
    'servmod.1': 'Full Charter', 'servmod.2': 'ACMI / Wet Lease', 'servmod.3': 'Cargo Charter', 'servmod.4': 'Damp Lease', 'servmod.5': 'Capacidad ociosa disponible',
  },
  en: {
    'nav.inicio': 'Home', 'nav.solicitar': 'Request Flight', 'nav.registrar': 'Register Fleet',
    'nav.servicios': 'Services', 'nav.como': 'How It Works', 'nav.ia': 'Responsible AI',
    'nav.empresa': 'Company', 'nav.contacto': 'Contact', 'nav.cta': 'Request Flight',
    'home.tag': 'Charter · ACMI · Cargo · Special Operations',
    'home.h1a': 'Idle fleet.', 'home.h1b': 'Real demand.',
    'home.sub1': 'We connect air demand with available fleet in less time.',
    'home.sub2': 'Charter flights, ACMI/Wet Lease, cargo and special operations coordinated with traceability, operational criteria and human review available.',
    'home.btn1': 'Request flight', 'home.btn2': 'Register fleet',
    'home.badge1': 'RESPONSE 24/7', 'home.badge2': 'QUOTE IN 2H', 'home.badge3': 'HUMAN REVIEW AVAILABLE',
    'home.hub.tag': 'Aviation Intelligence Hub', 'home.hub.title': 'Aviation Intelligence Hub',
    'home.hub.desc': 'We centralize flight requests, fleet availability and operational evaluation to connect real requirements with compatible air capacity.',
    'home.hub.i1t': 'Charter and ACMI', 'home.hub.i1d': 'Capacity for dedicated operations, wet lease and demand coverage.',
    'home.hub.i2t': 'Cargo and critical operations', 'home.hub.i2d': 'Fast evaluation for routes, urgent cargo, passengers or special missions.',
    'home.hub.i3t': 'Traceability and human review', 'home.hub.i3d': 'Requirement log, evaluation criteria and expert review when applicable.',
    'home.hub.footer': '24/7 operational response with accelerated evaluation for urgent requests.',
    'home.stat1': 'Global operators', 'home.stat2': 'Countries covered', 'home.stat3': 'Operational response', 'home.stat4': 'Urgent quote',
    'home.demand.tag': 'Demand', 'home.demand.title': 'Do you need to fly?',
    'home.demand.desc': 'For companies, agencies, governments, sports, logistics and special missions that need the right aircraft without losing time.',
    'home.demand.i1': 'Corporate and executive charter', 'home.demand.i2': 'Groups and delegations',
    'home.demand.i3': 'Urgent and specialized cargo', 'home.demand.i4': 'Medical or humanitarian operations',
    'home.demand.btn': 'Request flight',
    'home.bridge': 'FlyTriplatam connects both sides with operational criteria and traceability.',
    'home.offer.tag': 'Supply', 'home.offer.title': 'Do you have available fleet?',
    'home.offer.desc': 'For lessors, operators, charter providers and fleet owners seeking exposure to real demand and idle capacity.',
    'home.offer.i1': 'ACMI / Wet Lease', 'home.offer.i2': 'Full Charter', 'home.offer.i3': 'Cargo Charter', 'home.offer.i4': 'Idle capacity / availability',
    'home.offer.btn': 'Register fleet',
    'home.srv.tag': 'Services', 'home.srv.title': 'Charter aviation solutions',
    'home.srv.desc': 'Charter, ACMI, cargo and specialized flights for critical and coordinated demand.',
    'home.srv.link': 'View services',
    'home.srv.1t': 'ACMI / Wet Lease', 'home.srv.1d': 'Capacity with aircraft, crew, maintenance and insurance to cover demand peaks or operational continuity.',
    'home.srv.2t': 'Full Charter', 'home.srv.2d': 'Dedicated operations for groups, events, delegations and high-value movements with end-to-end coordination.',
    'home.srv.3t': 'Cargo and logistics', 'home.srv.3d': 'General, urgent, pharmaceutical, perishable and high-value cargo with focus on traceability and critical timelines.',
    'home.srv.4t': 'Executive and medical', 'home.srv.4d': 'Executive jets, air ambulance and medical transfers with expert coordination and human review available.',
    'home.coord.tag': 'Operational coordination', 'home.coord.title': 'Every request is evaluated with operational criteria',
    'home.coord.desc1': 'Each request is evaluated considering route, urgency, operation type, availability and technical restrictions.',
    'home.coord.desc2': 'We do not connect forms with databases. We connect real requirements with compatible operational capacity.',
    'home.coord.i1t': 'Validated demand', 'home.coord.i1d': 'The request enters with basic operational fit signals.',
    'home.coord.i2t': 'Compatible capacity', 'home.coord.i2d': 'Contrasted with available capacity and aircraft type.',
    'home.coord.i3t': 'Human review available', 'home.coord.i3d': 'Activated if the case requires expert criteria.',
    'home.how.tag': 'How it works', 'home.how.title': 'We turn an air need into traceable options',
    'home.how.desc': 'We capture information, evaluate supply and return options with human supervision available when the case requires it.',
    'home.how.link': 'View full process',
    'home.how.1t': 'We receive your requirement', 'home.how.1d': 'We capture route, urgency, operation type, passengers/cargo and restrictions.',
    'home.how.2t': 'We search for available aircraft', 'home.how.2d': 'We evaluate compatible capacity within a global network of operators and providers.',
    'home.how.3t': 'We deliver traceable options', 'home.how.3d': 'We present alternatives with human review available for critical cases.',
    'home.trust.tag': 'Operational trust',
    'home.trust.title': 'Processes designed for traceability, data protection, human review and continuous improvement.',
    'home.trust.desc1': 'The platform operates with visible controls and a document flow designed for sensitive B2B environments.',
    'home.trust.desc2': 'We designed the flow so the operation maintains control, traceability and human review when the case justifies it.',
    'home.trust.link': 'View responsible AI',
    'home.trust.i1t': 'Registration and operation', 'home.trust.i1d': 'TripLatam Ltd · UK Co. No. 15627355',
    'home.trust.i2t': 'Data protection', 'home.trust.i2d': 'Responsible handling of requests and commercial data.',
    'home.trust.i3t': 'Traceability', 'home.trust.i3d': 'Clear record of request, evaluation and proposal.',
    'home.trust.i4t': 'Human review', 'home.trust.i4d': 'Escalation available for critical operations.',
    'home.trust.i5t': 'Quality', 'home.trust.i5d': 'Processes aligned with good management practices.',
    'home.trust.i6t': 'Responsible AI', 'home.trust.i6d': 'Roadmap towards ISO/IEC 42001.',
    'home.cta.tag': 'Next step', 'home.cta.title': 'Request an operation or register available capacity.',
    'home.cta.desc': 'Request an operation or register available capacity in the FlyTriplatam network.',
    'home.cta.btn1': 'Request flight', 'home.cta.btn2': 'Register fleet',
    'home.cta.footer': '24/7 operational response · Human review available · Traceability and control',
    'srv.tag': 'Services', 'srv.title': 'Charter aviation solutions',
    'srv.desc': 'Charter, ACMI, cargo and specialized flights for critical and coordinated demand. Every operation evaluated with expert criteria.',
    'srv.inc': 'Includes', 'srv.cta.title': 'Do you need one of these solutions?',
    'srv.cta.desc': 'Send your requirement and we evaluate the operation with expert criteria. Response in less than 2 hours.',
    'srv.cta.btn1': 'Request flight', 'srv.cta.btn2': 'Contact',
    'srv.1t': 'ACMI / Wet Lease', 'srv.1d': 'Capacity with aircraft, crew, maintenance and insurance to cover demand peaks or operational continuity. Ideal for growing airlines, seasonal operations or fleet substitution.',
    'srv.1i1': 'Aircraft + crew + maintenance + insurance', 'srv.1i2': 'Routes defined by the lessee', 'srv.1i3': 'Flexible contracts by season or short term', 'srv.1i4': 'Ideal for covering demand peaks or ETOPS',
    'srv.2t': 'Full Charter', 'srv.2d': 'Dedicated operations for groups, events, delegations and high-value movements with end-to-end coordination. Exclusive flight for your operation.',
    'srv.2i1': 'Exclusive aircraft for your operation', 'srv.2i2': 'Customized itinerary', 'srv.2i3': 'Complete coordination from origin', 'srv.2i4': 'PRM, VIP and special protocol handling',
    'srv.3t': 'Cargo and logistics', 'srv.3d': 'General, urgent, pharmaceutical, perishable and high-value cargo with focus on traceability and critical timelines. Cold chain and dangerous goods handling.',
    'srv.3i1': 'General and urgent cargo', 'srv.3i2': 'Pharmaceutical products (temperature controlled)', 'srv.3i3': 'Dangerous goods per IATA DGR', 'srv.3i4': 'High traceability and documentation',
    'srv.4t': 'Executive and medical', 'srv.4d': 'Executive jets, air ambulance and medical transfers with expert coordination and human review available.',
    'srv.4i1': 'Executive and VIP jets', 'srv.4i2': 'Air ambulance (MEDEVAC)', 'srv.4i3': 'Patient repatriation', 'srv.4i4': 'Coordination with on-board medical teams',
    'how.tag': 'How it works', 'how.title': 'We turn an air need into traceable options',
    'how.desc': 'We capture information, evaluate supply and return options with human supervision available when the case requires it.',
    'how.coord.tag': 'Operational coordination', 'how.coord.title': 'Every request is evaluated with operational criteria',
    'how.coord.desc': 'We do not connect forms with databases. We connect real requirements with compatible operational capacity.',
    'how.coord.i1t': 'Validated demand', 'how.coord.i1d': 'The request enters with basic operational fit signals.',
    'how.coord.i2t': 'Compatible capacity', 'how.coord.i2d': 'Contrasted with available capacity and aircraft type.',
    'how.coord.i3t': 'Human review available', 'how.coord.i3d': 'Activated if the case requires expert criteria.',
    'how.btn1': 'Request flight', 'how.btn2': 'View responsible AI',
    'how.1t': 'We receive your requirement', 'how.1d': 'We capture route, urgency, operation type, passengers or cargo, and technical or regulatory restrictions.',
    'how.1i1': 'Structured request form', 'how.1i2': 'Basic operational fit signals', 'how.1i3': 'Automatic urgency classification', 'how.1i4': 'Initial requirement verification',
    'how.2t': 'We search for available aircraft', 'how.2d': 'We evaluate compatible capacity within a global network of operators, lessors and charter providers.',
    'how.2i1': 'Contrast with registered available fleet', 'how.2i2': 'Route and restriction evaluation', 'how.2i3': 'Compatible operator identification', 'how.2i4': 'Response time analysis',
    'how.3t': 'Operational evaluation', 'how.3d': 'Each request is evaluated considering route, urgency, operation type, availability and technical restrictions.',
    'how.3i1': 'Expert operational criteria', 'how.3i2': 'Aircraft-route fit validation', 'how.3i3': 'Human review for critical cases', 'how.3i4': 'Escalation for complex operations',
    'how.4t': 'We deliver traceable options', 'how.4d': 'We present alternatives with human review available for critical cases, with complete process traceability.',
    'how.4i1': 'Proposal with comparable options', 'how.4i2': 'Visible evaluation record', 'how.4i3': 'Human supervision in critical cases', 'how.4i4': 'Complete process documentation',
    'emp.tag': 'Company', 'emp.title': 'FlyTriplatam',
    'emp.desc': 'Aviation Intelligence Hub operated by TripLatam Ltd. We connect global air demand with available capacity in an agile, traceable and responsible way.',
    'emp.mis.tag': 'Our mission', 'emp.mis.title': 'Reducing friction between real air demand and available capacity.',
    'emp.mis.p1': 'The charter aviation market operates with structural inefficiencies: idle fleet that cannot find demand, and operations that cannot find suitable aircraft in time.',
    'emp.mis.p2': 'FlyTriplatam exists to resolve that gap with operational criteria, traceability and human review available when the case requires it.',
    'emp.dif.tag': 'What sets us apart',
    'emp.dif.1': 'We are not a criterionless marketplace: we evaluate every request operationally.',
    'emp.dif.2': 'Human review available for complex or critical cases.',
    'emp.dif.3': 'Complete process traceability: the requester knows how their operation was evaluated.',
    'emp.dif.4': 'Global operator network with presence in more than 80 countries.',
    'emp.dif.5': 'Response in less than 2 hours for urgent requests.',
    'emp.legal.tag': 'Legal registration', 'emp.legal.reg': 'TripLatam Ltd', 'emp.legal.ops': 'Operations', 'emp.legal.comp': 'Compliance',
    'emp.btn1': 'Contact', 'emp.btn2': 'Responsible AI',
    'cont.tag': 'Contact', 'cont.title': 'Contact',
    'cont.desc': 'We respond through the official site channels. For flight requests, use the structured form for a faster response.',
    'cont.c1t': 'Flight request', 'cont.c1d': 'For charter flights, ACMI, cargo and special operations.', 'cont.c1cta': 'Send email',
    'cont.c2t': 'Operational WhatsApp', 'cont.c2d': 'Direct channel for urgent requests and operational queries.', 'cont.c2cta': 'Open WhatsApp',
    'cont.c3t': 'Partnerships and operators', 'cont.c3d': 'For lessors, operators and charter providers looking to partner.', 'cont.c3cta': 'Send email',
    'cont.form.tag': 'Via form', 'cont.form.title': 'Structured request',
    'cont.form.desc': 'For charter, ACMI or cargo operations, the structured form allows us to evaluate your requirement in more detail and respond in less than 2 hours.',
    'cont.form.btn1': 'Flight request form', 'cont.form.btn2': 'Register available fleet',
    'ia.tag': 'Responsible AI', 'ia.title': 'Responsible AI',
    'ia.desc': 'Processes designed for traceability, data protection, human review and continuous improvement. The platform operates with visible controls and a document flow designed for sensitive B2B environments.',
    'ia.p1t': 'Operational transparency', 'ia.p1d': 'Evaluation processes are visible and traceable. The requester can understand how their requirement was evaluated and what criteria were applied.',
    'ia.p2t': 'Human review available', 'ia.p2d': 'For critical, complex or sensitive operations, a human expert reviews and validates the process before presenting options.',
    'ia.p3t': 'Data protection', 'ia.p3d': 'Commercial and operational data is handled responsibly, under UK GDPR, with limited access and documented flows.',
    'ia.p4t': 'Audit logs and traceability', 'ia.p4d': 'Clear record of request, evaluation and proposal. Every operation leaves a verifiable documentary trail.',
    'ia.design.tag': 'Design principle', 'ia.design.quote': 'We designed the flow so the operation maintains control, traceability and human review when the case justifies it.',
    'ia.road.tag': 'Status and roadmap',
    'ia.r1l': 'Human review available', 'ia.r1d': 'Active manual escalation for critical operations.',
    'ia.r2l': 'Basic audit logs', 'ia.r2d': 'Request and response logging on every operation.',
    'ia.r3l': 'UK GDPR compliance', 'ia.r3d': 'Data handling compliant with UK regulation.',
    'ia.r4l': 'ISO 9001 alignment', 'ia.r4d': 'Quality processes aligned with the international standard.',
    'ia.r5l': 'ISO/IEC 42001 certification', 'ia.r5d': 'Roadmap towards AI systems certification.',
    'ia.r6l': 'Explainability reports', 'ia.r6d': 'Explainability reports for each automatic evaluation.',
    'ia.status.active': 'Active', 'ia.status.process': 'In progress', 'ia.status.roadmap': 'Roadmap',
    'ia.comp.tag': 'Registration and compliance', 'ia.comp.std': 'Standards',
    'ia.btn1': 'View full process', 'ia.btn2': 'Contact for more information',
    'reg.tag': 'Supply', 'reg.title': 'Register fleet',
    'reg.desc': 'Register your aircraft or fleet in the FlyTriplatam network and access real demand for charter, ACMI and cargo flights.',
    'reg.badge1': 'Global demand network', 'reg.badge2': 'No access costs', 'reg.badge3': 'Human match review',
    'reg.sec1': '01 — Operator details', 'reg.sec2': '02 — Aircraft details', 'reg.sec3': '03 — Available modalities', 'reg.sec4': '04 — Additional information',
    'reg.nombre': 'Contact name *', 'reg.empresa': 'Company / Operator *', 'reg.email': 'Email *',
    'reg.telefono': 'Phone / WhatsApp', 'reg.web': 'Website',
    'reg.aeronave': 'Aircraft type *', 'reg.matricula': 'Registration / Tail number', 'reg.anio': 'Year of manufacture',
    'reg.capacidad': 'Capacity (PAX or kg)', 'reg.bases': 'Operating bases', 'reg.disponibilidad': 'Next availability',
    'reg.desc_placeholder': 'Certifications, usual routes, special operating conditions, restrictions...',
    'reg.submit': 'Register fleet', 'reg.sending': 'Sending...', 'reg.select': 'Select...',
    'reg.privacy': 'By registering, you agree that we use this information to connect you with compatible demand in the FlyTriplatam network.',
    'reg.success_title': 'Fleet registered', 'reg.success_msg': 'Your fleet has been registered. Our team will review the information and get in touch with you.',
    'reg.error_msg': 'Error sending. Write to us at charter@triplatam.com',
    'form.title': 'Request a flight', 'form.subtitle': 'Fill in the form with your operation details. We evaluate your requirement and respond with traceable options in under 2 hours.',
    'form.badge1': 'Response in 2h', 'form.badge2': 'Human review available', 'form.badge3': 'No commitment',
    'form.sec1': '01 — Contact details', 'form.nombre': 'Full name *', 'form.empresa': 'Company / Organization',
    'form.email': 'Email *', 'form.telefono': 'Phone / WhatsApp', 'form.sec2': '02 — Operation type',
    'form.tipo': 'Operation type *', 'form.urgencia': 'Urgency *',
    'form.sec3.vuelo': '03 — Operation details', 'form.sec3.acmi': '03 — ACMI / Lease specifications',
    'form.trayecto': 'Route type *', 'form.origen': 'Origin *', 'form.destino': 'Destination *',
    'form.fecha': 'Departure date *', 'form.fecha_regreso': 'Return date *',
    'form.pax': 'Passengers / PAX', 'form.carga': 'Cargo / special restrictions',
    'form.acmi_tipo': 'Contract type *', 'form.acmi_aircraft': 'Required aircraft',
    'form.acmi_bhr': 'Estimated block hours / month', 'form.acmi_duracion': 'Contract duration',
    'form.acmi_aoc': 'Lessee AOC', 'form.acmi_base': 'Main operating base',
    'form.tramo': 'Leg', 'form.agregar_tramo': 'Add leg', 'form.sec4': '04 — Additional description',
    'form.desc_vuelo': 'Describe your operation in as much detail as possible: preferred aircraft type, itinerary, special conditions, etc.',
    'form.desc_acmi': 'Describe the ACMI requirement: planned routes, contract conditions, required certifications...',
    'form.consent': 'I agree to interact with an Artificial Intelligence Hyperagent.',
    'form.consent_desc': 'I understand that my request will be processed automatically by the CharterLink AI system. I can request human review at any time by contacting',
    'form.consent_error': '⚠ You must accept the consent to continue.',
    'form.ia_notice': 'You are interacting with an Artificial Intelligence Hyperagent. Your request will be processed automatically. If you prefer to speak with a human, write to us at',
    'form.legal': 'CharterLink by TripLatam Ltd · UK Co. No. 15627355 · Data processed under UK GDPR.',
    'form.legal_link': 'Do you disagree with an automatic decision? Request human review.',
    'form.submit': 'Send request', 'form.sending': 'Sending...', 'form.privacy': 'By submitting, you agree that we process your data to evaluate your operational request.',
    'form.success_title': 'Request sent', 'form.success_msg': 'Your request was sent successfully. We will contact you in less than 2 hours.',
    'form.error_msg': 'There was an error sending. Write to us directly at charter@triplatam.com', 'form.select': 'Select...',
    'tray.ow': 'One Way (OW)', 'tray.rt': 'Round Trip (RT)', 'tray.multi': 'Multi-leg',
    'urg.1': 'Urgent (< 24h)', 'urg.2': 'High (1-3 days)', 'urg.3': 'Normal (3-7 days)', 'urg.4': 'Planned (> 7 days)',
    'tipo.1': 'Passenger Charter', 'tipo.2': 'ACMI / Wet Lease', 'tipo.3': 'General Cargo', 'tipo.4': 'Urgent Cargo',
    'tipo.5': 'Medical / MEDEVAC', 'tipo.6': 'Humanitarian', 'tipo.7': 'Government / Military', 'tipo.8': 'Sports', 'tipo.9': 'Other',
    'acmi.1': 'Wet Lease (full ACMI)', 'acmi.2': 'Dry Lease (aircraft only)', 'acmi.3': 'Damp Lease (aircraft + crew)',
    'dur.1': '1 to 3 months', 'dur.2': '3 to 6 months', 'dur.3': '6 to 12 months', 'dur.4': 'More than 12 months', 'dur.5': 'Ad-hoc operation',
    'aeronave.1': 'Narrow-body (B737, A320 family)', 'aeronave.2': 'Wide-body (B767, A330)', 'aeronave.3': 'Regional Jet (E190, CRJ)',
    'aeronave.4': 'Turboprop (ATR, Dash 8)', 'aeronave.5': 'Freighter (B747F, B777F)', 'aeronave.6': 'Executive Jet', 'aeronave.7': 'Helicopter', 'aeronave.8': 'Other',
    'servmod.1': 'Full Charter', 'servmod.2': 'ACMI / Wet Lease', 'servmod.3': 'Cargo Charter', 'servmod.4': 'Damp Lease', 'servmod.5': 'Available idle capacity',
  }
};

const LangContext = createContext<LangContextType>({ lang: 'es', setLang: () => {}, t: (k) => k });

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('es');

  useEffect(() => {
    const saved = localStorage.getItem('flytriplatam-lang') as Lang | null;
    if (saved === 'es' || saved === 'en') setLang(saved);
  }, []);

  const handleSetLang = (l: Lang) => {
    setLang(l);
    localStorage.setItem('flytriplatam-lang', l);
  };

  const t = (key: string) => translations[lang][key] ?? key;
  return <LangContext.Provider value={{ lang, setLang: handleSetLang, t }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
